### ISSUE TITLE
Member lookup

### ISSUE THREAD

**Issue by xinjianguosccs** [sctcs/v2016#3]
3.member lookup系统，能不能增加一个以family ID or member ID查询的功能，最好能一查就可以把整个家庭的member查出来，这样比较容易找人。

**Comment by xinjianguosccs** [comment]
Shuang, when you are ready, you can start to work on this one. Let me know if you have any questions.

**Comment by yshgit** [comment]
can you send me the DDL for table setup?

**Comment by xinjianguosccs** [comment]
db dump was attached in yesterday's email

**Comment by yshgit** [comment]
can you send me the database dump again. I seem to lost the previous email

**Comment by xinjianguosccs** [comment]
emailed the db dump

**Comment by yshgit** [comment]
my implementation simply extended the MemberLookup.php
the query by last name now do one step furtherfirstly lookup familyidthen use familyid to get all members.
