### ISSUE TITLE
Style sheet broken?

### ISSUE THREAD

**Issue by xinjianguosccs** [sctcs/v2016#6]
prod_v14 is renamed as v2016/public, many pages look broken with formatting.

Pinxia may want to take a look.

**Comment by pinxia** [comment]
Will fix it tonight. 

发自我的 iPhone

**Comment by xinjianguosccs** [comment]
No rush, it does not impact back-end functions and development

**Comment by pinxia** [comment]
The "assets" folder that contains stylesheet is missing.

**Comment by pinxia** [comment]
Xinjian, 

I tried to push the assets folder to a branch to fix the broken link.  I received this error message:  "https://pinxia820%40gmail.com@github.com/sctcs/v2016: git-receive-pack not permitted"

Thank you, 
pinxia

**Comment by xinjianguosccs** [comment]
missing assets folder is added to public folder and the issue is resolved
